// <auto-generated />
using AP.BTP.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AP.BTP.Infrastructure.Migrations
{
    [DbContext(typeof(BTPContext))]
    [Migration("20250926194956_longmigration")]
    partial class longmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AP.BTP.Domain.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Brussels",
                            Population = 1800000L
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "Antwerp",
                            Population = 529000L
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 2,
                            Name = "Amsterdam",
                            Population = 872000L
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 2,
                            Name = "Rotterdam",
                            Population = 651000L
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 3,
                            Name = "Berlin",
                            Population = 3600000L
                        });
                });

            modelBuilder.Entity("AP.BTP.Domain.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Turkey"
                        });
                });

            modelBuilder.Entity("AP.BTP.Domain.City", b =>
                {
                    b.HasOne("AP.BTP.Domain.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
